# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
      NUGET_XMLDOC_MODE: skip
    steps:
      - name: Install nats
        run: |
          # latest 0.1.1 doesn't have binaries
          # rel=$(curl -s https://api.github.com/repos/nats-io/natscli/releases/latest | jq -r .tag_name | sed s/v//)
          rel=0.1.0
          wget https://github.com/nats-io/natscli/releases/download/v$rel/nats-$rel-linux-amd64.zip
          unzip nats-$rel-linux-amd64.zip
          sudo mv nats-$rel-linux-amd64/nats /usr/local/bin
          for i in 1 2 3
          do
            curl -sf https://binaries.nats.dev/nats-io/nats-server/v2@${{ matrix.config.branch }} | PREFIX=. sh && break || sleep 30
          done
          sudo mv nats-server /usr/local/bin
      - name: Check nats
        run: |
          nats --version
          nats-server -v
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
#      - name: Test
#        run: dotnet test --no-build --verbosity normal
